### ISSUE TITLE
Is this mod compatible with Skeletal Remains/Rotten Creatures/Enderman Overhaul/Creeper Overhaul?

### ISSUE THREAD

**Issue by seriousfreezing** [sf-inc/sihywtcamd#50]

**Comment by charlyb01** [comment]
Hello and thanks for the question! I am going to add a page for this in the wiki as this is the kind of question I often get, but I'll reply to you first here.

There is no mod **incompatibility**, that is you can **run** this mod with any other mod.  
This is different from "will the new [insert modded mob name] types have the modded features from your mod?". To this question, it is completely mod-dependant. I'm doing my best so that any modded mob will be compatible this way, but if a new zombie type is added, but not based on vanilla zombie, then my mod can't know it should apply to this new.

* **Skeletal Remains:** ✅ The only thing to note is that the Spectral arrows that should be only for regular Skeletons in my mod can apply to any of these new skeletons.
* **Rotten Creatures:** ✅
* **Enderman Overhaul:** ⚠️ My changes are Enderman specific **for now**. I just found how to make this more compatible, so it's going to be compatible in the next version! *(releasing soon)*
* **Creeper Overhaul:** ⚠️ Chain explosion should work. Explosion effects should apply only to the regular Creeper. Just like others, I didn't test but just read the code, I might be wrong. However, it seems that the new creepers variants override a lot of the base code.
