### ISSUE TITLE
Add "client" , "server and client" tags on modrinth

### ISSUE THREAD

**Issue by Dementore711** [sf-inc/sihywtcamd#66]
Please add "client" , "server and client" tags on modrinth . When this mod is added to mrpacks for download on a small community server, prism launcher automatically treats this as a server only mod and wont download it on client.

This causes sihywtcamd-extensions to throw an error saying sihywtcamd v1.11 is required

PS : Love this mod as it adds a challenge for long time players

**Comment by charlyb01** [comment]
Hi, thanks for the report! I added the "server and client" tag on Modrinth, it should be enough I guess?  
But the real issue is that the extension mod shouldn't require the base mod to avoid this kind of issue. I will keep the issue open as long as I don't have updated the extension mod to not require it

**Comment by charlyb01** [comment]
I updated the mod and the extension. The extension mod doesn't require the base mod anymore. The base mod is only required on the server, if you don't have it on the client, everything will still work as expected :)
